/**
 * English copy for the app-shell screens introduced by the PWA redesign.
 *
 * Deviation note (see AGENTS.md): the shared i18n catalogue
 * `src/lib/i18n/messages.ts` is outside this branch's allowed files, so
 * new-shell copy is English-only for v1 and lives here. The guided
 * assessment step screens keep their full i18n via `t()`. Folding these
 * strings into messages.ts is a flagged additive follow-up.
 */
export const shellCopy = {
  signIn: {
    headline: "Move with more confidence.",
    supporting: "Simple mobility checks, progress history, and nearby support.",
    continueGoogle: "Continue with Google",
    signingIn: "Signing in…",
    googleError:
      "Google sign-in didn’t complete. You can try again or explore with the Mr Tan demo.",
    continueMobile: "Continue with mobile number",
    continueEmail: "Continue with email",
    comingSoon: "Coming soon",
    carePartner: "Care partner sign in",
    demo: "Continue with Mr Tan demo",
    privacy: "Your assessment records stay private and secure.",
    stubNote:
      "Mobile and email sign-in are coming soon. Use the Mr Tan demo to explore the app.",
  },
  tabs: {
    assessment: "Assessment",
    community: "Community",
    resources: "Resources",
  },
  home: {
    todayTitle: "Today’s mobility check",
    todayDuration: "Takes about 4 minutes",
    startAssessment: "Start assessment",
    lastResultTitle: "Last result",
    nextStepTitle: "Recommended next step",
    nextStepBody: "Try 8-minute balance practice",
    openExercise: "Open exercise",
    historyTitle: "Recent checks",
    viewAllHistory: "View all history",
    reassurance: "There are no wrong answers.",
  },
  flow: {
    stage: (current: number, total: number) => `Stage ${current} of ${total}`,
    exit: "Exit",
    exitTitle: "Leave this check?",
    exitBody:
      "Your answers so far will not be saved. You can start again any time.",
    exitConfirm: "Leave check",
    exitCancel: "Keep going",
    loadSample: "Load sample answers (Mr Tan)",
    sampleLoaded: "Sample answers loaded — you can change any of them.",
  },
  hub: {
    title: "Assessment",
    intro: "Do the checks in any order. Your progress is saved on this device.",
    precheckTitle: "Consent & safety check",
    precheckSupport: "Needed once before the tests.",
    testsHeading: "Mobility checks",
    activityHeading: "Keep moving",
    tests: {
      self_confidence: "Self confidence",
      sit_to_stand: "Sit to stand",
      walk: "Walk test",
      floor_rising: "Floor rising",
      timed_up_and_go: "Timed up and go",
      functional_reach: "Functional reach",
    },
    exerciseTitle: "Exercise",
    exerciseSupport: "Guided videos — always available",
    status: {
      notStarted: "Not started",
      inProgress: "In progress",
      done: "Done",
      skipped: "Skipped",
      available: "Open anytime",
    },
    locks: {
      consent_required: "Finish the consent & safety check first",
      safety_check_required: "Finish the safety check first",
      safety_flagged: "Paused for safety today",
      prerequisite: "Do the previous test first",
      coming_soon: "Coming soon",
    },
    actions: {
      start: "Start",
      continue: "Continue",
      redo: "Redo",
      open: "Open",
    },
    finish: "Finish & review",
    finishHint: "Complete at least one check to finish.",
    startOver: "Start over",
    startOverTitle: "Start over?",
    startOverBody:
      "This clears everything in today’s check, including consent and any test results that are not saved to history yet.",
    startOverConfirm: "Clear and start over",
    startOverCancel: "Keep my answers",
    precheckDone: "Done",
    exerciseBody:
      "Gentle guided movement helps keep strength and balance between checks. Exercise is practice, not an assessment — it never affects your results.",
    exerciseOpenVideos: "Open exercise videos",
    exerciseMarkDone: "Mark as done today",
    exerciseLoggedToday: "Logged for today",
  },
  precheck: {
    title: "Consent & safety check",
    next: "Next",
    done: "Done — back to hub",
    backToHub: "Back to hub",
  },
  test: {
    doneBackToHub: "Done — back to hub",
  },
  result: {
    title: "Assessment complete",
    partialHeadline: "Check recorded",
    partialBody:
      "Complete the confidence questions and sit-to-stand test for a full summary.",
    notDonePrefix: "Not done this time:",
    saveToHistory: "Save to history",
    savedOnDevice: "Saved on this device",
    openReport: "Open clinician report (print / PDF)",
    viewResources: "View resources",
    backToAssessment: "Back to Assessment",
  },
  trends: {
    title: "Your progress",
    emptyState: "Complete another assessment to see trends.",
    metrics: {
      overall: "Overall result",
      confidence: "Confidence",
      sit_to_stand: "Sit to stand",
      gait_speed: "Walking speed",
      floor_rising: "Floor rising",
      timed_up_and_go: "Timed up and go",
      functional_reach: "Functional reach",
    },
    // "Changed" (not "declined") — honest neutral wording with the values
    // shown alongside; never alarming, never diagnostic.
    direction: {
      improved: "Improved",
      steady: "Steady",
      declined: "Changed",
    },
    missingTitle: "Not compared this time",
    summaryTitle: "Summary",
    summaryTitleAi: "AI summary",
  },
  history: {
    title: "Assessment History",
    viewDetails: "View details",
    detailTitle: "Assessment detail",
    samplePill: "Sample",
    sampleTrend: "Sample history — Mr Tan demo",
    empty: "No saved checks yet. Complete today’s mobility check to start your journal.",
  },
  community: {
    title: "Community",
    goalTitle: (days: number) => `${days}-day movement goal`,
    goalReached: "Goal reached",
    goalDaysLeft: (days: number) => `${days} ${days === 1 ? "day" : "days"} left`,
    goalProgress: (goalDays: number, targetDays: number) =>
      `${goalDays} of ${targetDays} days this week — every gentle movement counts.`,
    logWalk: "Log a walk",
    logWalkPrompt: "How long did you walk?",
    logWalkCancel: "Cancel",
    walkDuration10: "10 min",
    walkDuration20: "20 min",
    walkDuration30: "30 min",
    walkLogged: "Walk logged — nice work.",
    sampleFeedNote: "Sample neighbourhood feed",
    samplePill: "Sample",
    optInTitle: "Share your movement with neighbours?",
    optInBody:
      "Sharing is off by default. Everything you’ve logged so far is private — only you can see it. Turning this on will show your movement activity to neighbours in Community.",
    optInAction: "Turn on community sharing",
    optInDismiss: "Keep private",
    emptyFeedTitle: "No neighbours are sharing yet",
    emptyFeedBody:
      "You’re in early — activity from opted-in neighbours will appear here.",
    yourActivityTitle: "Your activity this week",
    yourActivityEmpty: "No activity logged yet this week.",
  },
  resources: {
    title: "Resources",
    searchPlaceholder: "Search nearby support",
  },
  profile: {
    title: "Profile",
    signOut: "Sign out",
  },
  carePartner: {
    title: "Care partner access",
    body: "Help a family member review assessment summaries and nearby support.",
    inputPlaceholder: "Mobile number or invite code",
    continue: "Continue",
    backToSignIn: "Back to sign in",
    stubNote: "Care partner access is coming soon.",
  },
  privacy: {
    title: "Privacy & consent",
  },
  onboarding: {
    eyebrow: "Welcome to PhysioAid",
    step: (current: number, total: number) => `Step ${current} of ${total}`,
    continueLabel: "Continue",
    back: "Back",
    welcome: {
      title: "Let’s set up your profile",
      body: "A few quick questions help PhysioAid greet you properly, suggest nearby support, and keep your records private to you.",
      duration: "Takes about 2 minutes. You can change everything later.",
    },
    aboutYou: {
      title: "About you",
      support: "Everything here is optional — share what you’re comfortable with.",
      nameLabel: "What should we call you?",
      ageLabel: "Age group",
      livingLabel: "Living situation",
      areaLabel: "Neighbourhood",
      areaHelp: "Used only to suggest support near you. Never GPS.",
      areaNone: "—",
      languageLabel: "Preferred language",
      textSizeLabel: "Text size",
    },
    supportContact: {
      title: "Support contact",
      support:
        "A family member or care partner we can show next to your results. This is optional — you can skip it.",
      nameLabel: "Name",
      phoneLabel: "Mobile number",
      relationshipLabel: "Relationship",
      skip: "Skip for now",
    },
    consent: {
      title: "Your privacy choices",
      support:
        "You decide what PhysioAid may do. Nothing here is required, and you can change these any time in Profile.",
      assessmentLabel: "Assessment records",
      assessmentBody: "Save my mobility check answers and results to my private history.",
      aiLabel: "AI insights",
      aiBody: "Use my results to prepare plain-language summaries and suggestions.",
      communityLabel: "Community sharing",
      communityBody: "Show my movement activity to neighbours in the Community tab.",
      on: "On",
      off: "Off",
    },
    ready: {
      title: "You’re all set",
      body: "Here’s what we’ve saved. You can change any of it later in Profile.",
      nameLabel: "Name",
      ageLabel: "Age group",
      areaLabel: "Neighbourhood",
      contactLabel: "Support contact",
      consentsLabel: "Sharing choices",
      consentsSummary: (on: number, total: number) => `${on} of ${total} switched on`,
      notProvided: "Not provided",
      contactNone: "Not connected",
      start: "Start using PhysioAid",
    },
  },
} as const;
