import type { Language } from "@/lib/i18n/types";

/**
 * Copy for the app-shell screens introduced by the PWA redesign, translated
 * for every supported language. The guided assessment step screens keep
 * their own catalogue in `src/lib/i18n/messages.ts`; this file covers
 * onboarding, sign-in, tabs, and the dashboard shell so that picking a
 * language in onboarding actually applies across the whole app.
 *
 * `shellCopy` is keyed by `Language` — callers must select their language
 * via `useLanguage()` and read `shellCopy[lang]` (not `shellCopy` itself).
 */
const en = {
  signIn: {
    headline: "Move with more confidence.",
    supporting: "Simple mobility checks, progress history, and nearby support.",
    continueGoogle: "Continue with Google",
    signingIn: "Signing in…",
    googleError:
      "Google sign-in didn’t complete. You can try again or explore with the Mr Tan demo.",
    continueMobile: "Continue with mobile number",
    continueEmail: "Continue with email",
    comingSoon: "Coming soon",
    carePartner: "Care partner sign in",
    demo: "Continue with Mr Tan demo",
    privacy: "Your assessment records stay private and secure.",
    stubNote:
      "Mobile and email sign-in are coming soon. Use the Mr Tan demo to explore the app.",
  },
  tabs: {
    assessment: "Assessment",
    community: "Community",
    resources: "Resources",
  },
  home: {
    todayTitle: "Today’s mobility check",
    todayDuration: "Takes about 4 minutes",
    startAssessment: "Start assessment",
    lastResultTitle: "Last result",
    nextStepTitle: "Recommended next step",
    nextStepBody: "Try 8-minute balance practice",
    openExercise: "Open exercise",
    historyTitle: "Recent checks",
    viewAllHistory: "View all history",
    reassurance: "There are no wrong answers.",
  },
  flow: {
    stage: (current: number, total: number) => `Stage ${current} of ${total}`,
    exit: "Exit",
    exitTitle: "Leave this check?",
    exitBody:
      "Your answers so far will not be saved. You can start again any time.",
    exitConfirm: "Leave check",
    exitCancel: "Keep going",
    loadSample: "Load sample answers (Mr Tan)",
    sampleLoaded: "Sample answers loaded — you can change any of them.",
  },
  hub: {
    title: "Assessment",
    intro: "Do the checks in any order. Your progress is saved on this device.",
    precheckTitle: "Consent & safety check",
    precheckSupport: "Needed once before the tests.",
    testsHeading: "Mobility checks",
    activityHeading: "Keep moving",
    tests: {
      self_confidence: "Self confidence",
      sit_to_stand: "Sit to stand",
      walk: "Walk test",
      floor_rising: "Floor rising",
      timed_up_and_go: "Timed up and go",
      functional_reach: "Functional reach",
    },
    exerciseTitle: "Exercise",
    exerciseSupport: "Guided videos — always available",
    status: {
      notStarted: "Not started",
      inProgress: "In progress",
      done: "Done",
      skipped: "Skipped",
      available: "Open anytime",
    },
    locks: {
      consent_required: "Finish the consent & safety check first",
      safety_check_required: "Finish the safety check first",
      safety_flagged: "Paused for safety today",
      prerequisite: "Do the previous test first",
      coming_soon: "Coming soon",
    },
    actions: {
      start: "Start",
      continue: "Continue",
      redo: "Redo",
      open: "Open",
    },
    finish: "Finish & review",
    finishHint: "Complete at least one check to finish.",
    startOver: "Start over",
    startOverTitle: "Start over?",
    startOverBody:
      "This clears everything in today’s check, including consent and any test results that are not saved to history yet.",
    startOverConfirm: "Clear and start over",
    startOverCancel: "Keep my answers",
    precheckDone: "Done",
    exerciseBody:
      "Gentle guided movement helps keep strength and balance between checks. Exercise is practice, not an assessment — it never affects your results.",
    exerciseOpenVideos: "Open exercise videos",
    exerciseMarkDone: "Mark as done today",
    exerciseLoggedToday: "Logged for today",
  },
  precheck: {
    title: "Consent & safety check",
    next: "Next",
    done: "Done — back to hub",
    backToHub: "Back to hub",
  },
  test: {
    doneBackToHub: "Done — back to hub",
    continueToNext: "Continue",
    pause: "Pause",
  },
  result: {
    title: "Assessment complete",
    partialHeadline: "Check recorded",
    partialBody:
      "Complete the confidence questions and sit-to-stand test for a full summary.",
    notDonePrefix: "Not done this time:",
    saveToHistory: "Save to history",
    savedOnDevice: "Saved on this device",
    openReport: "Open clinician report (print / PDF)",
    viewResources: "View resources",
    backToAssessment: "Back to Assessment",
  },
  trends: {
    title: "Your progress",
    emptyState: "Complete another assessment to see trends.",
    metrics: {
      overall: "Overall result",
      confidence: "Confidence",
      sit_to_stand: "Sit to stand",
      gait_speed: "Walking speed",
      floor_rising: "Floor rising",
      timed_up_and_go: "Timed up and go",
      functional_reach: "Functional reach",
    },
    // "Changed" (not "declined") — honest neutral wording with the values
    // shown alongside; never alarming, never diagnostic.
    direction: {
      improved: "Improved",
      steady: "Steady",
      declined: "Changed",
    },
    missingTitle: "Not compared this time",
    summaryTitle: "Summary",
    summaryTitleAi: "AI summary",
  },
  history: {
    title: "Assessment History",
    viewDetails: "View details",
    detailTitle: "Assessment detail",
    samplePill: "Sample",
    sampleTrend: "Sample history — Mr Tan demo",
    empty: "No saved checks yet. Complete today’s mobility check to start your journal.",
  },
  community: {
    title: "Community",
    goalTitle: (days: number) => `${days}-day movement goal`,
    goalReached: "Goal reached",
    goalDaysLeft: (days: number) => `${days} ${days === 1 ? "day" : "days"} left`,
    goalProgress: (goalDays: number, targetDays: number) =>
      `${goalDays} of ${targetDays} days this week — every gentle movement counts.`,
    logWalk: "Log a walk",
    logWalkPrompt: "How long did you walk?",
    logWalkCancel: "Cancel",
    walkDuration10: "10 min",
    walkDuration20: "20 min",
    walkDuration30: "30 min",
    walkLogged: "Walk logged — nice work.",
    sampleFeedNote: "Sample neighbourhood feed",
    samplePill: "Sample",
    optInTitle: "Share your movement with neighbours?",
    optInBody:
      "Sharing is off by default. Everything you’ve logged so far is private — only you can see it. Turning this on will show your movement activity to neighbours in Community.",
    optInAction: "Turn on community sharing",
    optInDismiss: "Keep private",
    emptyFeedTitle: "No neighbours are sharing yet",
    emptyFeedBody:
      "You’re in early — activity from opted-in neighbours will appear here.",
    yourActivityTitle: "Your activity this week",
    yourActivityEmpty: "No activity logged yet this week.",
  },
  resources: {
    title: "Resources",
    searchPlaceholder: "Search nearby support",
  },
  profile: {
    title: "Profile",
    signOut: "Sign out",
    languageLabel: "Preferred language",
    textSizeLabel: "Text size",
    textSizeOptions: {
      standard: "Standard",
      large: "Large",
      xl: "Extra large",
    },
    yourProfileFallback: "Your profile",
    ageGroupPrefix: (ageGroup: string) => `Age group: ${ageGroup}`,
    carePartnerLabel: "Care partner",
    notConnected: "Not connected",
    remindersLabel: "Assessment reminders",
    weeklyReminderOn: "Weekly reminder on",
    remindersOff: "Reminders off",
    on: "On",
    off: "Off",
    privacyLabel: "Privacy and consent",
  },
  carePartner: {
    title: "Care partner access",
    body: "Help a family member review assessment summaries and nearby support.",
    phoneLabel: "Mobile number",
    phonePlaceholder: "e.g. 9123 4567",
    shareWhatsApp: "Send via WhatsApp",
    sent: "WhatsApp opened — send the message to invite them.",
    backToSignIn: "Back to sign in",
  },
  privacy: {
    title: "Privacy & consent",
  },
  onboarding: {
    eyebrow: "Welcome to PhysioAid",
    step: (current: number, total: number) => `Step ${current} of ${total}`,
    continueLabel: "Continue",
    back: "Back",
    welcome: {
      title: "Let’s set up your profile",
      body: "A few quick questions help PhysioAid greet you properly, suggest nearby support, and keep your records private to you.",
      duration: "Takes about 2 minutes. You can change everything later.",
    },
    aboutYou: {
      title: "About you",
      support: "Everything here is optional — share what you’re comfortable with.",
      nameLabel: "What should we call you?",
      ageLabel: "Age group",
      livingLabel: "Living situation",
      areaLabel: "Neighbourhood",
      areaHelp: "Used only to suggest support near you. Never GPS.",
      areaNone: "—",
      heightLabel: "Height in cm",
      languageLabel: "Preferred language",
      textSizeLabel: "Text size",
    },
    supportContact: {
      title: "Support contact",
      support:
        "A family member or care partner we can show next to your results. This is optional — you can skip it.",
      nameLabel: "Name",
      phoneLabel: "Mobile number",
      relationshipLabel: "Relationship",
      skip: "Skip for now",
    },
    consent: {
      title: "Your privacy choices",
      support:
        "You decide what PhysioAid may do. Nothing here is required, and you can change these any time in Profile.",
      assessmentLabel: "Assessment records",
      assessmentBody: "Save my mobility check answers and results to my private history.",
      aiLabel: "AI insights",
      aiBody: "Use my results to prepare plain-language summaries and suggestions.",
      communityLabel: "Community sharing",
      communityBody: "Show my movement activity to neighbours in the Community tab.",
      on: "On",
      off: "Off",
    },
    ready: {
      title: "You’re all set",
      body: "Here’s what we’ve saved. You can change any of it later in Profile.",
      nameLabel: "Name",
      ageLabel: "Age group",
      areaLabel: "Neighbourhood",
      contactLabel: "Support contact",
      consentsLabel: "Sharing choices",
      consentsSummary: (on: number, total: number) => `${on} of ${total} switched on`,
      notProvided: "Not provided",
      contactNone: "Not connected",
      start: "Start using PhysioAid",
    },
  },
};

const zh: ShellCopy = {
  signIn: {
    headline: "更有信心地活动。",
    supporting: "简单的行动能力检查、进度记录，以及附近的支持资源。",
    continueGoogle: "使用 Google 继续",
    signingIn: "正在登录…",
    googleError: "Google 登录未完成。您可以重试，或使用陈先生演示账号体验应用。",
    continueMobile: "使用手机号码继续",
    continueEmail: "使用电子邮箱继续",
    comingSoon: "即将推出",
    carePartner: "照顾者登录",
    demo: "使用陈先生演示账号继续",
    privacy: "您的评估记录将保持私密与安全。",
    stubNote: "手机号码和电子邮箱登录即将推出。请先使用陈先生演示账号体验应用。",
  },
  tabs: {
    assessment: "评估",
    community: "社区",
    resources: "资源",
  },
  home: {
    todayTitle: "今日行动能力检查",
    todayDuration: "大约需要 4 分钟",
    startAssessment: "开始评估",
    lastResultTitle: "上次结果",
    nextStepTitle: "建议的下一步",
    nextStepBody: "尝试 8 分钟平衡练习",
    openExercise: "打开练习",
    historyTitle: "近期检查",
    viewAllHistory: "查看全部记录",
    reassurance: "没有错误答案。",
  },
  flow: {
    stage: (current, total) => `第 ${current} 阶段，共 ${total} 阶段`,
    exit: "退出",
    exitTitle: "要离开此次检查吗？",
    exitBody: "目前的回答不会被保存。您可以随时重新开始。",
    exitConfirm: "离开检查",
    exitCancel: "继续进行",
    loadSample: "载入示例答案（陈先生）",
    sampleLoaded: "已载入示例答案——您可以修改其中任何一项。",
  },
  hub: {
    title: "评估",
    intro: "可按任意顺序完成检查。进度会保存在此设备上。",
    precheckTitle: "同意与安全检查",
    precheckSupport: "在测试前需要完成一次。",
    testsHeading: "行动能力检查",
    activityHeading: "保持活动",
    tests: {
      self_confidence: "自我信心",
      sit_to_stand: "坐立测试",
      walk: "步行测试",
      floor_rising: "地面起身",
      timed_up_and_go: "起立行走计时",
      functional_reach: "功能性伸展",
    },
    exerciseTitle: "运动练习",
    exerciseSupport: "引导视频——随时可用",
    status: {
      notStarted: "尚未开始",
      inProgress: "进行中",
      done: "已完成",
      skipped: "已跳过",
      available: "随时开放",
    },
    locks: {
      consent_required: "请先完成同意与安全检查",
      safety_check_required: "请先完成安全检查",
      safety_flagged: "今日因安全原因已暂停",
      prerequisite: "请先完成上一项测试",
      coming_soon: "即将推出",
    },
    actions: {
      start: "开始",
      continue: "继续",
      redo: "重做",
      open: "打开",
    },
    finish: "完成并查看",
    finishHint: "至少完成一项检查才能结束。",
    startOver: "重新开始",
    startOverTitle: "要重新开始吗？",
    startOverBody: "这将清除今日检查中的所有内容，包括同意信息以及尚未保存到记录中的测试结果。",
    startOverConfirm: "清除并重新开始",
    startOverCancel: "保留我的答案",
    precheckDone: "已完成",
    exerciseBody: "轻柔的引导运动有助于在检查之间保持力量与平衡。练习只是练习，不是评估——它不会影响您的结果。",
    exerciseOpenVideos: "打开练习视频",
    exerciseMarkDone: "标记为今日已完成",
    exerciseLoggedToday: "今日已记录",
  },
  precheck: {
    title: "同意与安全检查",
    next: "下一步",
    done: "完成——返回中心",
    backToHub: "返回中心",
  },
  test: {
    doneBackToHub: "完成——返回中心",
    continueToNext: "继续",
    pause: "暂停",
  },
  result: {
    title: "评估已完成",
    partialHeadline: "检查已记录",
    partialBody: "完成信心问题和坐立测试即可获得完整总结。",
    notDonePrefix: "本次未完成：",
    saveToHistory: "保存到记录",
    savedOnDevice: "已保存在此设备",
    openReport: "打开临床医生报告（打印 / PDF）",
    viewResources: "查看资源",
    backToAssessment: "返回评估",
  },
  trends: {
    title: "您的进展",
    emptyState: "再完成一次评估即可查看趋势。",
    metrics: {
      overall: "总体结果",
      confidence: "信心",
      sit_to_stand: "坐立测试",
      gait_speed: "步行速度",
      floor_rising: "地面起身",
      timed_up_and_go: "起立行走计时",
      functional_reach: "功能性伸展",
    },
    direction: {
      improved: "有所提升",
      steady: "保持稳定",
      declined: "有所变化",
    },
    missingTitle: "本次未比较",
    summaryTitle: "总结",
    summaryTitleAi: "AI 总结",
  },
  history: {
    title: "评估记录",
    viewDetails: "查看详情",
    detailTitle: "评估详情",
    samplePill: "示例",
    sampleTrend: "示例记录——陈先生演示",
    empty: "尚无保存的检查。完成今日的行动能力检查即可开始您的记录。",
  },
  community: {
    title: "社区",
    goalTitle: (days) => `${days} 天活动目标`,
    goalReached: "目标已达成",
    goalDaysLeft: (days) => `还剩 ${days} 天`,
    goalProgress: (goalDays, targetDays) =>
      `本周 ${targetDays} 天中已完成 ${goalDays} 天——每一次轻柔活动都很重要。`,
    logWalk: "记录一次步行",
    logWalkPrompt: "您步行了多久？",
    logWalkCancel: "取消",
    walkDuration10: "10 分钟",
    walkDuration20: "20 分钟",
    walkDuration30: "30 分钟",
    walkLogged: "步行已记录——做得好。",
    sampleFeedNote: "示例邻里动态",
    samplePill: "示例",
    optInTitle: "要与邻居分享您的活动吗？",
    optInBody: "默认关闭分享。您目前记录的一切都是私密的，只有您能看到。开启后，您的活动将显示给社区中的邻居。",
    optInAction: "开启社区分享",
    optInDismiss: "保持私密",
    emptyFeedTitle: "暂时还没有邻居分享内容",
    emptyFeedBody: "您来得比较早——已选择分享的邻居的活动会显示在这里。",
    yourActivityTitle: "您本周的活动",
    yourActivityEmpty: "本周尚未记录任何活动。",
  },
  resources: {
    title: "资源",
    searchPlaceholder: "搜索附近的支持资源",
  },
  profile: {
    title: "个人资料",
    signOut: "退出登录",
    languageLabel: "偏好语言",
    textSizeLabel: "文字大小",
    textSizeOptions: {
      standard: "标准",
      large: "大",
      xl: "特大",
    },
    yourProfileFallback: "您的个人资料",
    ageGroupPrefix: (ageGroup) => `年龄段：${ageGroup}`,
    carePartnerLabel: "照顾者",
    notConnected: "未连接",
    remindersLabel: "评估提醒",
    weeklyReminderOn: "每周提醒已开启",
    remindersOff: "提醒已关闭",
    on: "开启",
    off: "关闭",
    privacyLabel: "隐私与同意",
  },
  carePartner: {
    title: "照顾者访问",
    body: "协助家人查看评估总结与附近的支持资源。",
    phoneLabel: "手机号码",
    phonePlaceholder: "例如 9123 4567",
    shareWhatsApp: "通过 WhatsApp 发送",
    sent: "WhatsApp 已打开——发送消息以邀请他们。",
    backToSignIn: "返回登录",
  },
  privacy: {
    title: "隐私与同意",
  },
  onboarding: {
    eyebrow: "欢迎使用 PhysioAid",
    step: (current, total) => `第 ${current} 步，共 ${total} 步`,
    continueLabel: "继续",
    back: "返回",
    welcome: {
      title: "让我们设置您的个人资料",
      body: "几个简单问题能帮助 PhysioAid 更恰当地问候您、建议附近的支持资源，并保护您的记录隐私。",
      duration: "大约需要 2 分钟。之后您可以随时更改。",
    },
    aboutYou: {
      title: "关于您",
      support: "以下内容均为可选——分享您觉得自在的信息即可。",
      nameLabel: "我们该怎么称呼您？",
      ageLabel: "年龄段",
      livingLabel: "居住情况",
      areaLabel: "社区",
      areaHelp: "仅用于建议您附近的支持资源，绝不使用 GPS。",
      areaNone: "—",
      heightLabel: "身高（厘米）",
      languageLabel: "偏好语言",
      textSizeLabel: "文字大小",
    },
    supportContact: {
      title: "支持联系人",
      support: "可在您的结果旁显示的家人或照顾者。此项为可选，您可以跳过。",
      nameLabel: "姓名",
      phoneLabel: "手机号码",
      relationshipLabel: "关系",
      skip: "暂时跳过",
    },
    consent: {
      title: "您的隐私选择",
      support: "由您决定 PhysioAid 可以做什么。以下均非必填，您可随时在个人资料中更改。",
      assessmentLabel: "评估记录",
      assessmentBody: "将我的行动能力检查答案与结果保存到我的私人记录中。",
      aiLabel: "AI 洞察",
      aiBody: "使用我的结果生成简明总结与建议。",
      communityLabel: "社区分享",
      communityBody: "在社区标签页向邻居展示我的活动。",
      on: "开启",
      off: "关闭",
    },
    ready: {
      title: "一切就绪",
      body: "以下是我们已保存的信息。您可以随时在个人资料中更改。",
      nameLabel: "姓名",
      ageLabel: "年龄段",
      areaLabel: "社区",
      contactLabel: "支持联系人",
      consentsLabel: "分享选择",
      consentsSummary: (on, total) => `已开启 ${total} 项中的 ${on} 项`,
      notProvided: "未提供",
      contactNone: "未连接",
      start: "开始使用 PhysioAid",
    },
  },
};

const ms: ShellCopy = {
  signIn: {
    headline: "Bergerak dengan lebih yakin.",
    supporting: "Pemeriksaan mobiliti yang mudah, rekod kemajuan, dan sokongan berdekatan.",
    continueGoogle: "Teruskan dengan Google",
    signingIn: "Sedang log masuk…",
    googleError: "Log masuk Google tidak selesai. Anda boleh cuba lagi atau terokai dengan demo Encik Tan.",
    continueMobile: "Teruskan dengan nombor telefon",
    continueEmail: "Teruskan dengan e-mel",
    comingSoon: "Akan datang",
    carePartner: "Log masuk rakan penjaga",
    demo: "Teruskan dengan demo Encik Tan",
    privacy: "Rekod penilaian anda kekal peribadi dan selamat.",
    stubNote: "Log masuk melalui nombor telefon dan e-mel akan datang tidak lama lagi. Gunakan demo Encik Tan untuk meneroka aplikasi ini.",
  },
  tabs: {
    assessment: "Penilaian",
    community: "Komuniti",
    resources: "Sumber",
  },
  home: {
    todayTitle: "Semakan mobiliti hari ini",
    todayDuration: "Mengambil masa lebih kurang 4 minit",
    startAssessment: "Mula penilaian",
    lastResultTitle: "Keputusan terakhir",
    nextStepTitle: "Langkah seterusnya yang disyorkan",
    nextStepBody: "Cuba latihan keseimbangan 8 minit",
    openExercise: "Buka latihan",
    historyTitle: "Semakan terkini",
    viewAllHistory: "Lihat semua rekod",
    reassurance: "Tiada jawapan yang salah.",
  },
  flow: {
    stage: (current, total) => `Peringkat ${current} daripada ${total}`,
    exit: "Keluar",
    exitTitle: "Tinggalkan semakan ini?",
    exitBody: "Jawapan anda setakat ini tidak akan disimpan. Anda boleh mula semula bila-bila masa.",
    exitConfirm: "Tinggalkan semakan",
    exitCancel: "Teruskan",
    loadSample: "Muatkan jawapan contoh (Encik Tan)",
    sampleLoaded: "Jawapan contoh dimuatkan — anda boleh ubah mana-mana daripadanya.",
  },
  hub: {
    title: "Penilaian",
    intro: "Buat semakan mengikut apa-apa susunan. Kemajuan anda disimpan pada peranti ini.",
    precheckTitle: "Persetujuan & semakan keselamatan",
    precheckSupport: "Diperlukan sekali sahaja sebelum ujian.",
    testsHeading: "Semakan mobiliti",
    activityHeading: "Terus bergerak",
    tests: {
      self_confidence: "Keyakinan diri",
      sit_to_stand: "Duduk ke berdiri",
      walk: "Ujian berjalan",
      floor_rising: "Bangun dari lantai",
      timed_up_and_go: "Ujian bangun-dan-pergi",
      functional_reach: "Capaian fungsian",
    },
    exerciseTitle: "Senaman",
    exerciseSupport: "Video berpandu — sedia setiap masa",
    status: {
      notStarted: "Belum bermula",
      inProgress: "Sedang berjalan",
      done: "Selesai",
      skipped: "Dilangkau",
      available: "Buka bila-bila masa",
    },
    locks: {
      consent_required: "Selesaikan persetujuan & semakan keselamatan dahulu",
      safety_check_required: "Selesaikan semakan keselamatan dahulu",
      safety_flagged: "Dijeda untuk keselamatan hari ini",
      prerequisite: "Buat ujian sebelumnya dahulu",
      coming_soon: "Akan datang",
    },
    actions: {
      start: "Mula",
      continue: "Teruskan",
      redo: "Buat semula",
      open: "Buka",
    },
    finish: "Selesai & semak",
    finishHint: "Lengkapkan sekurang-kurangnya satu semakan untuk selesai.",
    startOver: "Mula semula",
    startOverTitle: "Mula semula?",
    startOverBody: "Ini akan mengosongkan semua dalam semakan hari ini, termasuk persetujuan dan sebarang keputusan ujian yang belum disimpan ke rekod.",
    startOverConfirm: "Kosongkan dan mula semula",
    startOverCancel: "Kekalkan jawapan saya",
    precheckDone: "Selesai",
    exerciseBody: "Pergerakan lembut berpandu membantu mengekalkan kekuatan dan keseimbangan antara semakan. Senaman adalah latihan, bukan penilaian — ia tidak menjejaskan keputusan anda.",
    exerciseOpenVideos: "Buka video senaman",
    exerciseMarkDone: "Tandakan selesai hari ini",
    exerciseLoggedToday: "Direkodkan untuk hari ini",
  },
  precheck: {
    title: "Persetujuan & semakan keselamatan",
    next: "Seterusnya",
    done: "Selesai — kembali ke hab",
    backToHub: "Kembali ke hab",
  },
  test: {
    doneBackToHub: "Selesai — kembali ke hab",
    continueToNext: "Teruskan",
    pause: "Jeda",
  },
  result: {
    title: "Penilaian selesai",
    partialHeadline: "Semakan direkodkan",
    partialBody: "Lengkapkan soalan keyakinan dan ujian duduk-ke-berdiri untuk ringkasan penuh.",
    notDonePrefix: "Belum selesai kali ini:",
    saveToHistory: "Simpan ke rekod",
    savedOnDevice: "Disimpan pada peranti ini",
    openReport: "Buka laporan klinisi (cetak / PDF)",
    viewResources: "Lihat sumber",
    backToAssessment: "Kembali ke Penilaian",
  },
  trends: {
    title: "Kemajuan anda",
    emptyState: "Lengkapkan penilaian lain untuk melihat trend.",
    metrics: {
      overall: "Keputusan keseluruhan",
      confidence: "Keyakinan",
      sit_to_stand: "Duduk ke berdiri",
      gait_speed: "Kelajuan berjalan",
      floor_rising: "Bangun dari lantai",
      timed_up_and_go: "Ujian bangun-dan-pergi",
      functional_reach: "Capaian fungsian",
    },
    direction: {
      improved: "Bertambah baik",
      steady: "Stabil",
      declined: "Berubah",
    },
    missingTitle: "Tidak dibandingkan kali ini",
    summaryTitle: "Ringkasan",
    summaryTitleAi: "Ringkasan AI",
  },
  history: {
    title: "Sejarah Penilaian",
    viewDetails: "Lihat butiran",
    detailTitle: "Butiran penilaian",
    samplePill: "Contoh",
    sampleTrend: "Sejarah contoh — demo Encik Tan",
    empty: "Belum ada semakan disimpan. Lengkapkan semakan mobiliti hari ini untuk mula jurnal anda.",
  },
  community: {
    title: "Komuniti",
    goalTitle: (days) => `Sasaran pergerakan ${days} hari`,
    goalReached: "Sasaran dicapai",
    goalDaysLeft: (days) => `${days} hari lagi`,
    goalProgress: (goalDays, targetDays) =>
      `${goalDays} daripada ${targetDays} hari minggu ini — setiap pergerakan lembut penting.`,
    logWalk: "Rekod jalan kaki",
    logWalkPrompt: "Berapa lama anda berjalan?",
    logWalkCancel: "Batal",
    walkDuration10: "10 min",
    walkDuration20: "20 min",
    walkDuration30: "30 min",
    walkLogged: "Jalan kaki direkodkan — syabas.",
    sampleFeedNote: "Suapan kejiranan contoh",
    samplePill: "Contoh",
    optInTitle: "Kongsi pergerakan anda dengan jiran?",
    optInBody: "Perkongsian dimatikan secara lalai. Semua yang direkodkan setakat ini adalah peribadi — hanya anda boleh lihat. Menghidupkan ini akan menunjukkan aktiviti pergerakan anda kepada jiran dalam Komuniti.",
    optInAction: "Hidupkan perkongsian komuniti",
    optInDismiss: "Kekal peribadi",
    emptyFeedTitle: "Belum ada jiran berkongsi lagi",
    emptyFeedBody: "Anda antara yang awal — aktiviti daripada jiran yang menyertai akan muncul di sini.",
    yourActivityTitle: "Aktiviti anda minggu ini",
    yourActivityEmpty: "Belum ada aktiviti direkodkan minggu ini.",
  },
  resources: {
    title: "Sumber",
    searchPlaceholder: "Cari sokongan berdekatan",
  },
  profile: {
    title: "Profil",
    signOut: "Log keluar",
    languageLabel: "Bahasa pilihan",
    textSizeLabel: "Saiz teks",
    textSizeOptions: {
      standard: "Standard",
      large: "Besar",
      xl: "Sangat besar",
    },
    yourProfileFallback: "Profil anda",
    ageGroupPrefix: (ageGroup) => `Kumpulan umur: ${ageGroup}`,
    carePartnerLabel: "Rakan penjaga",
    notConnected: "Tidak disambungkan",
    remindersLabel: "Peringatan penilaian",
    weeklyReminderOn: "Peringatan mingguan dihidupkan",
    remindersOff: "Peringatan dimatikan",
    on: "Hidup",
    off: "Mati",
    privacyLabel: "Privasi dan persetujuan",
  },
  carePartner: {
    title: "Akses rakan penjaga",
    body: "Bantu ahli keluarga menyemak ringkasan penilaian dan sokongan berdekatan.",
    phoneLabel: "Nombor telefon",
    phonePlaceholder: "cth. 9123 4567",
    shareWhatsApp: "Hantar melalui WhatsApp",
    sent: "WhatsApp dibuka — hantar mesej untuk menjemput mereka.",
    backToSignIn: "Kembali ke log masuk",
  },
  privacy: {
    title: "Privasi & persetujuan",
  },
  onboarding: {
    eyebrow: "Selamat datang ke PhysioAid",
    step: (current, total) => `Langkah ${current} daripada ${total}`,
    continueLabel: "Teruskan",
    back: "Kembali",
    welcome: {
      title: "Mari sediakan profil anda",
      body: "Beberapa soalan ringkas membantu PhysioAid menyapa anda dengan sewajarnya, mencadangkan sokongan berdekatan, dan menjaga rekod anda peribadi kepada anda sahaja.",
      duration: "Mengambil masa lebih kurang 2 minit. Anda boleh ubah semuanya kemudian.",
    },
    aboutYou: {
      title: "Tentang anda",
      support: "Semua di sini adalah pilihan — kongsi apa yang anda selesa.",
      nameLabel: "Apa panggilan yang sesuai untuk anda?",
      ageLabel: "Kumpulan umur",
      livingLabel: "Situasi tempat tinggal",
      areaLabel: "Kejiranan",
      areaHelp: "Digunakan hanya untuk mencadangkan sokongan berdekatan anda. Tidak sesekali GPS.",
      areaNone: "—",
      heightLabel: "Tinggi dalam cm",
      languageLabel: "Bahasa pilihan",
      textSizeLabel: "Saiz teks",
    },
    supportContact: {
      title: "Kenalan sokongan",
      support: "Ahli keluarga atau rakan penjaga yang boleh kami tunjukkan di sebelah keputusan anda. Ini pilihan — anda boleh langkau.",
      nameLabel: "Nama",
      phoneLabel: "Nombor telefon",
      relationshipLabel: "Hubungan",
      skip: "Langkau buat masa ini",
    },
    consent: {
      title: "Pilihan privasi anda",
      support: "Anda yang menentukan apa yang PhysioAid boleh lakukan. Tiada apa di sini yang diwajibkan, dan anda boleh ubah bila-bila masa dalam Profil.",
      assessmentLabel: "Rekod penilaian",
      assessmentBody: "Simpan jawapan dan keputusan semakan mobiliti saya ke rekod peribadi saya.",
      aiLabel: "Wawasan AI",
      aiBody: "Guna keputusan saya untuk menyediakan ringkasan dan cadangan bahasa mudah.",
      communityLabel: "Perkongsian komuniti",
      communityBody: "Tunjukkan aktiviti pergerakan saya kepada jiran dalam tab Komuniti.",
      on: "Hidup",
      off: "Mati",
    },
    ready: {
      title: "Semuanya sedia",
      body: "Berikut adalah apa yang kami simpan. Anda boleh ubah mana-mana kemudian dalam Profil.",
      nameLabel: "Nama",
      ageLabel: "Kumpulan umur",
      areaLabel: "Kejiranan",
      contactLabel: "Kenalan sokongan",
      consentsLabel: "Pilihan perkongsian",
      consentsSummary: (on, total) => `${on} daripada ${total} dihidupkan`,
      notProvided: "Tidak disediakan",
      contactNone: "Tidak disambungkan",
      start: "Mula guna PhysioAid",
    },
  },
};

const ta: ShellCopy = {
  signIn: {
    headline: "மேலும் நம்பிக்கையுடன் இயங்குங்கள்.",
    supporting: "எளிய இயக்கத் திறன் சோதனைகள், முன்னேற்ற வரலாறு, மற்றும் அருகிலுள்ள ஆதரவு.",
    continueGoogle: "Google மூலம் தொடரவும்",
    signingIn: "உள்நுழைகிறது…",
    googleError: "Google உள்நுழைவு முடிவடையவில்லை. மீண்டும் முயற்சிக்கலாம் அல்லது திரு. டான் டெமோவைப் பயன்படுத்தி ஆராயலாம்.",
    continueMobile: "மொபைல் எண் மூலம் தொடரவும்",
    continueEmail: "மின்னஞ்சல் மூலம் தொடரவும்",
    comingSoon: "விரைவில் வரும்",
    carePartner: "பராமரிப்பாளர் உள்நுழைவு",
    demo: "திரு. டான் டெமோ மூலம் தொடரவும்",
    privacy: "உங்கள் மதிப்பீட்டுப் பதிவுகள் தனிப்பட்டதாகவும் பாதுகாப்பாகவும் இருக்கும்.",
    stubNote: "மொபைல் மற்றும் மின்னஞ்சல் உள்நுழைவு விரைவில் வரும். செயலியை ஆராய திரு. டான் டெமோவைப் பயன்படுத்துங்கள்.",
  },
  tabs: {
    assessment: "மதிப்பீடு",
    community: "சமூகம்",
    resources: "வளங்கள்",
  },
  home: {
    todayTitle: "இன்றைய இயக்கத் திறன் சோதனை",
    todayDuration: "சுமார் 4 நிமிடங்கள் ஆகும்",
    startAssessment: "மதிப்பீட்டைத் தொடங்கு",
    lastResultTitle: "கடைசி முடிவு",
    nextStepTitle: "பரிந்துரைக்கப்பட்ட அடுத்த படி",
    nextStepBody: "8 நிமிட சமநிலைப் பயிற்சியை முயற்சிக்கவும்",
    openExercise: "பயிற்சியைத் திற",
    historyTitle: "சமீபத்திய சோதனைகள்",
    viewAllHistory: "அனைத்து வரலாற்றையும் காண்க",
    reassurance: "தவறான பதில்கள் இல்லை.",
  },
  flow: {
    stage: (current, total) => `நிலை ${current} / ${total}`,
    exit: "வெளியேறு",
    exitTitle: "இந்தச் சோதனையை விட்டு வெளியேறவா?",
    exitBody: "இதுவரையிலான உங்கள் பதில்கள் சேமிக்கப்படாது. நீங்கள் எப்போது வேண்டுமானாலும் மீண்டும் தொடங்கலாம்.",
    exitConfirm: "சோதனையை விட்டு வெளியேறு",
    exitCancel: "தொடரவும்",
    loadSample: "மாதிரி பதில்களை ஏற்று (திரு. டான்)",
    sampleLoaded: "மாதிரி பதில்கள் ஏற்றப்பட்டன — நீங்கள் அவற்றில் எதையும் மாற்றலாம்.",
  },
  hub: {
    title: "மதிப்பீடு",
    intro: "எந்த வரிசையிலும் சோதனைகளைச் செய்யலாம். உங்கள் முன்னேற்றம் இந்தச் சாதனத்தில் சேமிக்கப்படுகிறது.",
    precheckTitle: "ஒப்புதல் & பாதுகாப்பு சரிபார்ப்பு",
    precheckSupport: "சோதனைகளுக்கு முன் ஒருமுறை தேவை.",
    testsHeading: "இயக்கத் திறன் சோதனைகள்",
    activityHeading: "தொடர்ந்து இயங்குங்கள்",
    tests: {
      self_confidence: "சுய நம்பிக்கை",
      sit_to_stand: "உட்கார்ந்திருந்து நிற்றல்",
      walk: "நடைப் பயிற்சி",
      floor_rising: "தரையிலிருந்து எழுதல்",
      timed_up_and_go: "நேரம் குறித்த எழுந்து செல்லும் சோதனை",
      functional_reach: "செயல்பாட்டு எட்டல்",
    },
    exerciseTitle: "பயிற்சி",
    exerciseSupport: "வழிகாட்டப்பட்ட காணொளிகள் — எப்போதும் கிடைக்கும்",
    status: {
      notStarted: "தொடங்கவில்லை",
      inProgress: "நடந்து கொண்டிருக்கிறது",
      done: "முடிந்தது",
      skipped: "தவிர்க்கப்பட்டது",
      available: "எப்போது வேண்டுமானாலும் திறக்கலாம்",
    },
    locks: {
      consent_required: "முதலில் ஒப்புதல் & பாதுகாப்பு சரிபார்ப்பை முடிக்கவும்",
      safety_check_required: "முதலில் பாதுகாப்பு சரிபார்ப்பை முடிக்கவும்",
      safety_flagged: "இன்று பாதுகாப்பிற்காக இடைநிறுத்தப்பட்டது",
      prerequisite: "முந்தைய சோதனையை முதலில் செய்யவும்",
      coming_soon: "விரைவில் வரும்",
    },
    actions: {
      start: "தொடங்கு",
      continue: "தொடரவும்",
      redo: "மீண்டும் செய்",
      open: "திற",
    },
    finish: "முடித்து மதிப்பாய்வு செய்",
    finishHint: "முடிக்க குறைந்தது ஒரு சோதனையையாவது முடிக்கவும்.",
    startOver: "மீண்டும் தொடங்கு",
    startOverTitle: "மீண்டும் தொடங்கவா?",
    startOverBody: "இது இன்றைய சோதனையிலுள்ள அனைத்தையும் அழிக்கும், ஒப்புதல் மற்றும் வரலாற்றில் இன்னும் சேமிக்கப்படாத சோதனை முடிவுகள் உட்பட.",
    startOverConfirm: "அழித்து மீண்டும் தொடங்கு",
    startOverCancel: "எனது பதில்களை வைத்திரு",
    precheckDone: "முடிந்தது",
    exerciseBody: "மென்மையான வழிகாட்டப்பட்ட இயக்கம் சோதனைகளுக்கு இடையில் வலிமையையும் சமநிலையையும் பராமரிக்க உதவுகிறது. பயிற்சி என்பது ஒரு பயிற்சியே, மதிப்பீடு அல்ல — இது உங்கள் முடிவுகளை ஒருபோதும் பாதிக்காது.",
    exerciseOpenVideos: "பயிற்சி காணொளிகளைத் திற",
    exerciseMarkDone: "இன்று முடிந்ததாகக் குறி",
    exerciseLoggedToday: "இன்றைக்குப் பதிவு செய்யப்பட்டது",
  },
  precheck: {
    title: "ஒப்புதல் & பாதுகாப்பு சரிபார்ப்பு",
    next: "அடுத்து",
    done: "முடிந்தது — மையத்திற்குத் திரும்பு",
    backToHub: "மையத்திற்குத் திரும்பு",
  },
  test: {
    doneBackToHub: "முடிந்தது — மையத்திற்குத் திரும்பு",
    continueToNext: "தொடரவும்",
    pause: "இடைநிறுத்து",
  },
  result: {
    title: "மதிப்பீடு முடிந்தது",
    partialHeadline: "சோதனை பதிவு செய்யப்பட்டது",
    partialBody: "முழு சுருக்கத்திற்கு நம்பிக்கை கேள்விகளையும் உட்கார்ந்து-நிற்கும் சோதனையையும் முடிக்கவும்.",
    notDonePrefix: "இந்த முறை முடிக்கப்படவில்லை:",
    saveToHistory: "வரலாற்றில் சேமி",
    savedOnDevice: "இந்தச் சாதனத்தில் சேமிக்கப்பட்டது",
    openReport: "மருத்துவ அறிக்கையைத் திற (அச்சு / PDF)",
    viewResources: "வளங்களைக் காண்க",
    backToAssessment: "மதிப்பீட்டிற்குத் திரும்பு",
  },
  trends: {
    title: "உங்கள் முன்னேற்றம்",
    emptyState: "போக்குகளைக் காண மற்றொரு மதிப்பீட்டை முடிக்கவும்.",
    metrics: {
      overall: "ஒட்டுமொத்த முடிவு",
      confidence: "நம்பிக்கை",
      sit_to_stand: "உட்கார்ந்திருந்து நிற்றல்",
      gait_speed: "நடை வேகம்",
      floor_rising: "தரையிலிருந்து எழுதல்",
      timed_up_and_go: "நேரம் குறித்த எழுந்து செல்லும் சோதனை",
      functional_reach: "செயல்பாட்டு எட்டல்",
    },
    direction: {
      improved: "மேம்பட்டது",
      steady: "நிலையானது",
      declined: "மாறியது",
    },
    missingTitle: "இந்த முறை ஒப்பிடப்படவில்லை",
    summaryTitle: "சுருக்கம்",
    summaryTitleAi: "AI சுருக்கம்",
  },
  history: {
    title: "மதிப்பீட்டு வரலாறு",
    viewDetails: "விவரங்களைக் காண்க",
    detailTitle: "மதிப்பீட்டு விவரம்",
    samplePill: "மாதிரி",
    sampleTrend: "மாதிரி வரலாறு — திரு. டான் டெமோ",
    empty: "இதுவரை சேமிக்கப்பட்ட சோதனைகள் இல்லை. உங்கள் பதிவேட்டைத் தொடங்க இன்றைய இயக்கத் திறன் சோதனையை முடிக்கவும்.",
  },
  community: {
    title: "சமூகம்",
    goalTitle: (days) => `${days}-நாள் இயக்க இலக்கு`,
    goalReached: "இலக்கு அடையப்பட்டது",
    goalDaysLeft: (days) => `${days} நாட்கள் மீதம்`,
    goalProgress: (goalDays, targetDays) =>
      `இந்த வாரம் ${targetDays} நாட்களில் ${goalDays} நாட்கள் — ஒவ்வொரு மென்மையான இயக்கமும் முக்கியம்.`,
    logWalk: "நடையைப் பதிவு செய்",
    logWalkPrompt: "எவ்வளவு நேரம் நடந்தீர்கள்?",
    logWalkCancel: "ரத்து செய்",
    walkDuration10: "10 நிமி",
    walkDuration20: "20 நிமி",
    walkDuration30: "30 நிமி",
    walkLogged: "நடை பதிவு செய்யப்பட்டது — நல்ல வேலை.",
    sampleFeedNote: "மாதிரி அக்கம்-பக்கச் செய்திகள்",
    samplePill: "மாதிரி",
    optInTitle: "உங்கள் இயக்கத்தை அண்டை வீட்டாருடன் பகிரவா?",
    optInBody: "பகிர்வு இயல்பாக நிறுத்தப்பட்டுள்ளது. இதுவரை நீங்கள் பதிவு செய்த அனைத்தும் தனிப்பட்டவை — உங்களால் மட்டுமே பார்க்க முடியும். இதை இயக்கினால், உங்கள் இயக்கச் செயல்பாடு சமூகத்தில் அண்டை வீட்டாருக்குக் காட்டப்படும்.",
    optInAction: "சமூகப் பகிர்வை இயக்கு",
    optInDismiss: "தனிப்பட்டதாக வை",
    emptyFeedTitle: "இன்னும் யாரும் பகிரவில்லை",
    emptyFeedBody: "நீங்கள் ஆரம்பத்தில் இருக்கிறீர்கள் — பங்கேற்ற அண்டை வீட்டாரின் செயல்பாடு இங்கே தோன்றும்.",
    yourActivityTitle: "இந்த வாரம் உங்கள் செயல்பாடு",
    yourActivityEmpty: "இந்த வாரம் இதுவரை எந்தச் செயல்பாடும் பதிவு செய்யப்படவில்லை.",
  },
  resources: {
    title: "வளங்கள்",
    searchPlaceholder: "அருகிலுள்ள ஆதரவைத் தேடுங்கள்",
  },
  profile: {
    title: "சுயவிவரம்",
    signOut: "வெளியேறு",
    languageLabel: "விருப்பமான மொழி",
    textSizeLabel: "எழுத்து அளவு",
    textSizeOptions: {
      standard: "நிலையானது",
      large: "பெரியது",
      xl: "மிகப் பெரியது",
    },
    yourProfileFallback: "உங்கள் சுயவிவரம்",
    ageGroupPrefix: (ageGroup) => `வயது குழு: ${ageGroup}`,
    carePartnerLabel: "பராமரிப்பாளர்",
    notConnected: "இணைக்கப்படவில்லை",
    remindersLabel: "மதிப்பீட்டு நினைவூட்டல்கள்",
    weeklyReminderOn: "வாராந்திர நினைவூட்டல் இயக்கப்பட்டது",
    remindersOff: "நினைவூட்டல்கள் நிறுத்தப்பட்டன",
    on: "இயக்கு",
    off: "நிறுத்து",
    privacyLabel: "தனியுரிமை மற்றும் ஒப்புதல்",
  },
  carePartner: {
    title: "பராமரிப்பாளர் அணுகல்",
    body: "மதிப்பீட்டு சுருக்கங்கள் மற்றும் அருகிலுள்ள ஆதரவை மதிப்பாய்வு செய்ய குடும்ப உறுப்பினருக்கு உதவுங்கள்.",
    phoneLabel: "மொபைல் எண்",
    phonePlaceholder: "எ.கா. 9123 4567",
    shareWhatsApp: "WhatsApp மூலம் அனுப்பு",
    sent: "WhatsApp திறக்கப்பட்டது — அவர்களை அழைக்க செய்தியை அனுப்புங்கள்.",
    backToSignIn: "உள்நுழைவுக்குத் திரும்பு",
  },
  privacy: {
    title: "தனியுரிமை & ஒப்புதல்",
  },
  onboarding: {
    eyebrow: "PhysioAid-க்கு வரவேற்கிறோம்",
    step: (current, total) => `படி ${current} / ${total}`,
    continueLabel: "தொடரவும்",
    back: "பின்",
    welcome: {
      title: "உங்கள் சுயவிவரத்தை அமைப்போம்",
      body: "சில விரைவான கேள்விகள் PhysioAid உங்களை முறையாக வரவேற்கவும், அருகிலுள்ள ஆதரவை பரிந்துரைக்கவும், உங்கள் பதிவுகளை தனிப்பட்டதாக வைக்கவும் உதவும்.",
      duration: "சுமார் 2 நிமிடங்கள் ஆகும். பின்னர் நீங்கள் எதையும் மாற்றலாம்.",
    },
    aboutYou: {
      title: "உங்களைப் பற்றி",
      support: "இங்குள்ள அனைத்தும் விருப்பமானவை — நீங்கள் வசதியாக உணரும் தகவலைப் பகிரவும்.",
      nameLabel: "உங்களை என்ன அழைக்க வேண்டும்?",
      ageLabel: "வயது குழு",
      livingLabel: "வாழ்க்கை சூழல்",
      areaLabel: "அக்கம்-பக்கம்",
      areaHelp: "உங்களுக்கு அருகிலுள்ள ஆதரவை பரிந்துரைக்க மட்டுமே பயன்படுத்தப்படும். GPS ஒருபோதும் இல்லை.",
      areaNone: "—",
      heightLabel: "உயரம் (செ.மீ.)",
      languageLabel: "விருப்பமான மொழி",
      textSizeLabel: "எழுத்து அளவு",
    },
    supportContact: {
      title: "ஆதரவு தொடர்பு",
      support: "உங்கள் முடிவுகளுக்கு அருகில் நாங்கள் காட்டக்கூடிய குடும்ப உறுப்பினர் அல்லது பராமரிப்பாளர். இது விருப்பமானது — நீங்கள் தவிர்க்கலாம்.",
      nameLabel: "பெயர்",
      phoneLabel: "மொபைல் எண்",
      relationshipLabel: "உறவு",
      skip: "தற்போதைக்குத் தவிர்",
    },
    consent: {
      title: "உங்கள் தனியுரிமை தேர்வுகள்",
      support: "PhysioAid என்ன செய்யலாம் என்பதை நீங்கள் தீர்மானிக்கிறீர்கள். இங்கு எதுவும் கட்டாயமில்லை, மேலும் நீங்கள் இவற்றை எப்போது வேண்டுமானாலும் சுயவிவரத்தில் மாற்றலாம்.",
      assessmentLabel: "மதிப்பீட்டுப் பதிவுகள்",
      assessmentBody: "எனது இயக்கத் திறன் சோதனை பதில்கள் மற்றும் முடிவுகளை எனது தனிப்பட்ட வரலாற்றில் சேமி.",
      aiLabel: "AI நுண்ணறிவுகள்",
      aiBody: "எளிய மொழி சுருக்கங்கள் மற்றும் பரிந்துரைகளைத் தயாரிக்க எனது முடிவுகளைப் பயன்படுத்து.",
      communityLabel: "சமூகப் பகிர்வு",
      communityBody: "சமூகக் கீற்றில் எனது இயக்கச் செயல்பாட்டை அண்டை வீட்டாருக்குக் காட்டு.",
      on: "இயக்கு",
      off: "நிறுத்து",
    },
    ready: {
      title: "அனைத்தும் தயார்",
      body: "நாங்கள் சேமித்தவை இதோ. பின்னர் சுயவிவரத்தில் எதையும் மாற்றலாம்.",
      nameLabel: "பெயர்",
      ageLabel: "வயது குழு",
      areaLabel: "அக்கம்-பக்கம்",
      contactLabel: "ஆதரவு தொடர்பு",
      consentsLabel: "பகிர்வு தேர்வுகள்",
      consentsSummary: (on, total) => `${total} இல் ${on} இயக்கப்பட்டது`,
      notProvided: "வழங்கப்படவில்லை",
      contactNone: "இணைக்கப்படவில்லை",
      start: "PhysioAid பயன்படுத்தத் தொடங்கு",
    },
  },
};

export type ShellCopy = typeof en;

/**
 * Localized shell copy. Callers must read `shellCopy[lang]`, using the
 * `lang` from `useLanguage()`, so the selected onboarding language applies
 * across the whole app rather than only the guided assessment screens.
 */
export const shellCopy: Record<Language, ShellCopy> = { en, zh, ms, ta };
